project:
  type: book

book:
  title: "Lezioni di demografia"
  author: "Marco Biffino"
  date: "01/01/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - 01_pop_demo.qmd
    - 02_fonti_qualita.qmd
    - 03_sviluppo_demo.qmd
    - 04_concetti_strumenti.qmd
    - 05_analisi_fenomeni_demo.qmd
    - 06_tavole_mortalita.qmd
    - 07_mortalita_approfondimenti.qmd
    - 08_form_scioglim_coppie.qmd
    - 09_fecondita.qmd
    - 10_fecondita_controllata.qmd
    - 11_mobilita_migrazioni.qmd
    - 12_modelli_popolazione.qmd
    - 99_rif_bibliografici.qmd

bibliography: bibliografia.bib

format:
  html:
    theme: cosmo

lang: it 
language: 
  it:
    crossref-sec-prefix: "Paragrafo"