project:
  type: book

book:
  title: "Lezioni di demografia"
  author: "Marco Biffino"
  date: "01/01/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - pop_demo.qmd
    - fonti_qualita.qmd
    - sviluppo_demo.qmd
    - concetti_strumenti.qmd
    - analisi_fenomeni_demo.qmd
    - tavole_mortalita.qmd
    - mortalita_approfondimenti.qmd
    - form_scioglim_coppie.qmd
    - fecondita.qmd
    - fecondita_controllata.qmd
    - mobilita_migrazioni.qmd
    - modelli_popolazione.qmd
    - rif_bibliografici.qmd

bibliography: bibliografia.bib

format:
  html:
    theme: cosmo