# Lezioni di demografia {.unnumbered}

## Presentazione {.unnumbered}

In questo testo potete (potrete, in realtà) trovare una raccolta dei materiali didattici che utilizzo durante le mie lezioni private di demografia destinate a studenti universitari.

Si tratta di materiali che hanno la loro origine nella seconda metà degli anni 2000 ampiamente ispirati e basati sul manuale @LiviBacci1999 Livi Bacci, *Introduzione alla demografia* di cui all'inizio erano dei riassunti. 

Il materiale nel corso del tempo è stato integrato con manuali più aggiornati, con esempi svolti e codice in linguaggio R per risolvere i più comuni problemi di calcolo.

## Note e raccomandazioni per il lettore

*In prepazione...*

## Licenza {.unnumbered}

La presente opera è rilasciata sotto licenza Creative Commons - Attribution - Share Alike

**Tu sei libero di**:

  Condividere — riprodurre, distribuire, comunicare al pubblico, esporre in pubblico, rappresentare, eseguire e recitare questo materiale con qualsiasi mezzo e formato per qualsiasi fine, anche commerciale.
  
  Modificare — remixare, trasformare il materiale e basarti su di esso per le tue opere per qualsiasi fine, anche commerciale.
  
  Il licenziante non può revocare questi diritti fintanto che tu rispetti i termini della licenza.
  
**Alle seguenti condizioni**:

  Attribuzione — Devi riconoscere una menzione di paternità adeguata, fornire un link alla licenza e indicare se sono state effettuate delle modifiche. Puoi fare ciò in qualsiasi maniera ragionevole possibile, ma non con modalità tali da suggerire che il licenziante avalli te o il tuo utilizzo del materiale.
  
  Stessa Licenza — Se remixi, trasformi il materiale o ti basi su di esso, devi distribuire i tuoi contributi con la stessa licenza del materiale originario.
  
  Divieto di restrizioni aggiuntive — Non puoi applicare termini legali o misure tecnologiche che impongano ad altri soggetti dei vincoli giuridici su quanto la licenza consente loro di fare.
  
Note:

Non sei tenuto a rispettare i termini della licenza per quelle componenti del materiale che siano in pubblico dominio o nei casi in cui il tuo utilizzo sia consentito da una eccezione o limitazione prevista dalla legge.

Non sono fornite garanzie. La licenza può non conferirti tutte le autorizzazioni necessarie per l'utilizzo che ti prefiggi. Ad esempio, diritti di terzi come i diritti all'immagine, alla riservatezza e i diritti morali potrebbero restringere gli usi che ti prefiggi sul materiale.

Avviso

Questo riassunto illustra solo alcuni degli elementi e dei termini chiave della licenza vera e propria. Non è una licenza ed è privo di valore legale. Devi leggere attentamente tutti i termini e le condizioni della licenza vera e propria prima di utilizzare il materiale concesso in licenza.

Creative Commons non è uno studio legale e non fornisce servizi legali. La distribuzione, l'esposizione o il collegamento a questo riassunto o alla licenza che esso illustra non instaura un rapporto avvocato-cliente né rapporti di altro tipo.

